import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../../layout/Default";
import styles from "../../../styles/Brochures.module.scss";
import Hero from "../../components/Brochures/Hero";
import React, { Component, useState } from "react";
import Slider from "react-slick";
import { Document, Page } from "react-pdf";

const Brochures: NextPage = ({ brochure }: any) => {
  console.log(brochure);
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }: { numPages: any }) {
    setNumPages(numPages);
  }

  return (
    <>
      <LayoutDefault>
        <Hero />
        <div className="container">
          <Head>
            <title>Stratoz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.title_desc}>
              <div className={"container " + styles.mb65}>
                <h2 className={styles.h2_title}>
                  <span>Brochures</span>
                </h2>
                <hr />

                {brochure.brochure.map((value: any, i: number) => (
                  <div className={"row " + styles.mb35} key={i}>
                    <div className="col-md-12">
                      <h5 className={styles.titleh5}>{value.title}</h5>
                      <Document
                        file={ `${process.env.NEXT_PUBLIC_API_BASE_URL}${value.brochure[0]?.url}` }
                        onLoadSuccess={onDocumentLoadSuccess}
                      >
                        <Page pageNumber={pageNumber} />
                      </Document>
                      <p>
                        Page {pageNumber} of {numPages}
                      </p>

                      {/* <img src="/brochures1.png" width="100%"/> */}

                      <div className="row">
                        <div className={"col-md-6 "+ styles.mt25}>
                          <a href={ `${process.env.NEXT_PUBLIC_API_BASE_URL}${value.brochure[0]?.url}` }>
                            <button className={styles.broBtn }>
                              <img src="/icons/download.png" />
                              Download
                            </button>
                          </a>
                        </div>
                        <div className={"col-md-6 text-end " + styles.mt25 + " "+ styles.slideBtn}>
                          <button><img src="/icons/left.png"/></button>
                          <button><img src="/icons/right.png"/></button>
                        </div>
                      </div>
                    </div>
                  </div>
                 ))}
              </div>
            </div>
          </main>
        </div>
      </LayoutDefault>
    </>
  );
};

export async function getStaticProps() {
  
  // Fetch all categories form API
  const brochures = await fetch(`${process.env.API_BASE_URL}/brochures`);
  
  const brochure = await brochures.json();

  return {
    props: { brochure },
    revalidate: 1,
  };
}

export default Brochures;
