import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../../layout/Default";
import styles from "../../../styles/Blog.module.scss";
import Hero from "../../components/Blog/Hero";

const Blog: NextPage = ({ blog }: any) => {
  console.log(blog);
  
  return (
    <>
      <LayoutDefault>
        <Hero />
        <div className={styles.container}>
          <Head>
            <title>Stratoz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.title_desc}>
              <div className={"container " + styles.mb50}>
                <h2 className={styles.h2_title}>
                  <span>Our</span> Blog
                </h2>
                {/* <p>
                  Design a space perfectly tailored for your personal needs and
                  transform the everyday bathroom experience with our range of
                  products. It is the freedom to create a space that is
                  connected to one’s own senses and needs – a place for inner
                  contemplation, regeneration, and revitalization{" "}
                </p> */}
              </div>
            </div>
            <div className={styles.products}>
              <div className="container">
                <div className="row">
                  {blog.map((data: any, index: number) => (
                    <div key={index} className="col-md-4">
                      <a href={`/blog/${data.slug}`}>
                        <div className={styles.col4img + " " + styles.overlay}>
                          <Image
                            src={
                              data?.thumbnail
                                ? `${process.env.NEXT_PUBLIC_API_BASE_URL}${data?.thumbnail?.url}`
                                : "/products/5.png"
                            }
                            alt={data.title}
                            height="100%"
                            width="100%"
                            layout="responsive"
                          />
                        </div>
                        <div className={styles.text + " " + styles.shortText}>
                          <h6 className={styles.active}>{data.title}</h6>
                          <p>{data.content}</p>
                        </div>
                      </a>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </main>
        </div>
      </LayoutDefault>
    </>
  );
};

export async function getServerSideProps() {
  // Fetch all blogs form API
  const blogs = await fetch(`${process.env.API_BASE_URL}/blogs`);

  const blog = await blogs.json();

  // Pass data to the page via props
  return { props: { blog } };
}

export default Blog;
