import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../../../layout/Default";
import styles from "../../../../styles/Blog.module.scss";
import ReactHtmlParser from 'react-html-parser';
import hStyle from "../../../components/Blog/Hero/Hero.module.scss";

const Blog: NextPage = ({ blog, slug }: any) => {
  let base= process.env.NEXT_PUBLIC_API_BASE_URL;
  
  return (
    <>
      <LayoutDefault>
        <div className={styles.container}>
          <Head>
            <title>Stratoz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <br />
        <br />
        <br />
        <div className={hStyle.hero} style={{ backgroundImage: "url("+base+"/"+ blog.banner.url+")"}}>
          <div className="container">
            <h1>
              {blog.title}
            </h1>
          </div>
        </div>
        <div className="mb-5"></div>
        <div className="mt-5"></div>
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              { ReactHtmlParser(blog.content) }
              <br/>
              <br/>
              <h5>Written by {blog.author}</h5>
            </div>
          </div>
        </div>
      </LayoutDefault>
    </>
  );
};

export async function getServerSideProps({ query }: any) {
  // Fetch product list form API
  const blogData = await fetch(
    `${process.env.API_BASE_URL}/blogs/${query.slug}/`
  );

  const blog = await blogData.json();

  // Pass data to the page via props
  return { props: { blog, slug: query.slug } };
}

export default Blog;
