import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../../layout/Default";
import styles from "../../../styles/Collections.module.scss";
import Hero from "../../components/Collections/Hero";
import React, { Component, useState } from "react";

const Collections: NextPage = ({ collections }: any) => {
  return (
    <>
      <LayoutDefault>
        <Hero />
        <div className={styles.container}>
          <Head>
            <title>Stratoz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.title_desc}>
              <div className={"container " + styles.mb70}>
                {console.log(collections)}
                <div id="collections__grid">
                  <div className="container">
                    {collections &&
                      collections.map((collection: any, index: number) => {
                        return (
                          <>
                            <div className="item" key={index}>
                              <div className={styles.overlay}>
                                <img
                                  src={`${process.env.NEXT_PUBLIC_API_BASE_URL}${collection?.thumbnail?.url}`}
                                  className={styles.image}
                                />
                                <div className={styles.middle}>
                                  <a href={`/collections/${collection.slug}`}>
                                    <div className={styles.text}>
                                      {collection.title}
                                    </div>
                                  </a>
                                </div>
                              </div>
                            </div>
                          </>
                        );
                      })}
                  </div>
                </div>
                {/* <div className={styles.row + " mt-4"}>
                  <div className={styles.col5}>
                    <div className={styles.overlayHalf}>
                      <img
                        src="/collections/1.png"
                        className={styles.overlayImg}
                      />
                      <a href="/collections/alask">
                        <div className={styles.overlayContent}>ALASK</div>
                      </a>
                    </div>
                  </div>
                  <div className={styles.col7}>
                    <div className={styles.row + " " + styles.mb40}>
                      <div className={styles.col4}>
                        <div className={styles.overlay}>
                          <img
                            src="/collections/2.png"
                            className={styles.image}
                          />
                          <div className={styles.middle}>
                            <a href="/collections/orion">
                              <div className={styles.text}>ORION</div>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className={styles.col4}>
                        <div className={styles.overlay}>
                          <img
                            src="/collections/3.png"
                            className={styles.image}
                          />
                          <div className={styles.middle}>
                            <a href="/collections/orion">
                              <div className={styles.text}>ARAZ</div>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className={styles.col4}>
                        <div className={styles.overlay}>
                          <img
                            src="/collections/4.png"
                            className={styles.image}
                          />
                          <div className={styles.middle}>
                            <a href="/collections/orion">
                              <div className={styles.text}>FUSION</div>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={styles.row}>
                      <div className={styles.col4}>
                        <div className={styles.overlay}>
                          <img
                            src="/collections/5.png"
                            className={styles.image}
                          />
                          <div className={styles.middle}>
                            <a href="/collections/orion">
                              <div className={styles.text}>MIRRORS</div>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className={styles.col8}>
                        <div className={styles.overlay}>
                          <img
                            src="/collections/6.png"
                            className={styles.image}
                          />
                          <div className={styles.middle}>
                            <a href="/collections/orion">
                              <div className={styles.text}>OVO</div>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div> */}
              </div>
            </div>
          </main>
        </div>
      </LayoutDefault>
    </>
  );
};

export async function getServerSideProps() {
  // Fetch all categories form API
  const collectionsRes = await fetch(`${process.env.API_BASE_URL}/collections`);

  const collections = await collectionsRes.json();

  // Pass data to the page via props
  return { props: { collections } };
}

export default Collections;
