import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../../../layout/Default";
import styles from "../../../../styles/Favorites.module.scss";

const Favorites: NextPage = ({ products, category }: any) => {
  return (
    <>
      <LayoutDefault>
        <div className={styles.container}>
          <Head>
            <title>Stratos</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.title_desc}>
              <div className={"container " + styles.mb50}>
                <h2 className={styles.h2_title}>
                  <span>Favourite {category}</span> Products
                </h2>
                {console.log(products)}
                <hr />
              </div>
            </div>
            <div className={styles.products}>
              <div className="container">
                <div className={styles.row}>
                  {products.map((product: any) => (
                    <>
                      <div className={styles.col4}>
                        <div className={styles.col4fav}>
                          <div className={styles.fIcon}>
                            <img src="/icons/like.svg" />
                          </div>
                          <img src="/product2.png" />
                          <div className={styles.favDetails}>
                            <h4>{product.title}</h4>
                            <h5>product_code - color</h5>
                          </div>
                        </div>
                      </div>
                    </>
                  ))}
                </div>
              </div>
            </div>
            <div className={styles.navigation}>
              <div className="container">
                <div className={styles.row}>
                  <div className={styles.col12}>
                    <ul>
                      <li className={styles.active}>1</li>
                      <li>2</li>
                      <li>3</li>
                      <li>4</li>
                      <li>5</li>
                      <li>6</li>
                      <li>Next</li>
                      <li>Previous</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </LayoutDefault>
    </>
  );
};

// This gets called on every request
export async function getServerSideProps({ query }: any) {
  console.log("Query", query);

  // Fetch data from external API
  const res = await fetch(
    `http://192.168.1.13:1339/products?category.slug=${query.category}`
  );

  const data = await res.json();

  // Pass data to the page via props
  return { props: { products: data, category: query.category } };
}

export default Favorites;
