import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../layout/Default";
import styles from "../../styles/Brochures.module.scss";
import Hero from "../components/Brochures/Hero";
import React, { Component } from "react";
import Slider from "react-slick";

const Brochures: NextPage = () => {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
  };
  return (
    <>
      <LayoutDefault>
        <Hero />
        <div className={styles.container}>
          <Head>
            <title>Stratos</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.title_desc}>
              <div className={"container " + styles.mb65}>
                <h2 className={styles.h2_title}>
                  <span>Brochures</span> 
                </h2>
                <hr/>
                <div className={styles.row+" "+styles.mb35}>
                  <div className={styles.col12}>
                    <h5 className={styles.titleh5}>Sanitary Wares</h5>
                    {/* <Slider {...settings}>
                      <div>
                        1
                      </div>
                      <div>
                        2
                      </div>
                      <div>
                        3
                      </div>
                    </Slider> */}
                    <img src="/brochures1.png"/>
                    <button className={styles.broBtn+" "+styles.mt25}><img src="/icons/download.png"/>Download</button>
                  </div>
                </div>
                <div className={styles.row}>
                  <div className={styles.col12}>
                    <h5 className={styles.titleh5}>COLORS OF ART</h5>
                    <img src="/brochures2.png"/>
                    <button className={styles.broBtn+" "+styles.mt25}><img src="/icons/download.png"/>Download</button>
                  </div>
                </div>
              </div>
              
            </div>
            
          </main>
        </div>
      </LayoutDefault>
    </>
  );
};

export default Brochures;
