import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../layout/Default";
import styles from "../../styles/Home.module.scss";
import Sliders from "../components/Home/Slider";
import React, { Component } from "react";
import Slider from "react-slick";

const Home: NextPage = () => {
  const slider = React.useRef(null);
  const simDesignslider = React.useRef(null);
  const excRangeslider = React.useRef(null);
  const preSlider = React.useRef(null);
  
  const settings = {
    dots: false,
    infinite: false,
    speed: 500,
    slidesToShow: 1.09,
    slidesToScroll: 1
  };
  const simDesignsettings = {
    dots: false,
    infinite: false,
    slidesToShow: 3.9,
    slidesToScroll: 1,
    vertical: true,
    verticalSwiping: true,
    arrows: false
  };
  const excRangesettings1 = {
    dots: false,
    infinite: false,
    slidesToShow: 2.5,
    slidesToScroll: 1,
    vertical: true,
    verticalSwiping: true,
    arrows: false,
  };
  const excRangesettings2 = {
    dots: false,
    slidesToShow: 2.5,
    slidesToScroll: 1,
    vertical: true,
    verticalSwiping: true,
    arrows: false,
    centerMode: true,
    infinite: true,
    centerPadding: "60px",
  };
  const preSettings = {
    dots: false,
    infinite: false,
    speed: 500,
    slidesToShow: 3.5,
    slidesToScroll: 3,
    arrows: false
  };
  const bgSlidesettings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false
  };

  return (
    <>
      <LayoutDefault>

      {/* <div id="carouselExampleIndicators" className="carousel slide" data-ride="carousel">
        <ol className="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" className="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div className="carousel-inner">
          <div className="carousel-item active">
            <img className="d-block w-100" src="/banner.png"/>
          </div>
          <div className="carousel-item">
            <img className="d-block w-100" src="/banner.png"/>
          </div>
          <div className="carousel-item">
            <img className="d-block w-100" src="/banner.png"/>
          </div>
        </div>
      </div> */}

        <Sliders/>
        <main className={styles.main}>
          <div className="container">
            <Head>
              <title>Stratos</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={"row " + styles.exProducts}>
              <div className={"col-md-12 " + styles.mb35}>
                <h3>Explore <span>Products</span></h3>

                <Slider ref={slider} {...settings}>
                  <div>
                    <div className={"row"}>
                      <div className={"col-md-6 " + styles.col6}>
                        <div className={styles.epImages}>
                          <img src="/home/1.png"/>
                          <h3>EXPERIENCE <br/><span>THE SPIRITS OF WATER</span></h3>
                        </div>
                      </div>
                      <div className={"col-md-5 " + styles.col5}>
                        <div className={"row"}>
                          <div className={"col-md-12 " + styles.mb25}>
                            <div className={styles.epImages}>
                              <img src="/home/2.png"/>
                              <h3>SENSUAL <br/><span>MOMENTS</span></h3>
                            </div>
                          </div>
                          <div className="col-md-12">
                            <div className={styles.epImages}>
                              <img src="/home/3.png"/>
                              <h3>THE CLASSIC <br/><span>INTERPRETED</span></h3>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <div className={"row"}>
                      <div className={"col-md-6 " + styles.col6}>
                        <div className={styles.epImages}>
                          <img src="/home/1.png"/>
                          <h3>EXPERIENCE <br/><span>THE SPIRITS OF WATER</span></h3>
                        </div>
                      </div>
                      <div className={"col-md-5 " + styles.col5}>
                        <div className={"row"}>
                          <div className={"col-md-12 " + styles.mb25}>
                            <div className={styles.epImages}>
                              <img src="/home/2.png"/>
                              <h3>SENSUAL <br/><span>MOMENTS</span></h3>
                            </div>
                          </div>
                          <div className="col-md-12">
                            <div className={styles.epImages}>
                              <img src="/home/3.png"/>
                              <h3>THE CLASSIC <br/><span>INTERPRETED</span></h3>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </Slider>
              </div>
              <div className="col-md-6 col-6">
                <button onClick={() => slider?.current?.slickPrev()}><img src="/icons/left.png"/></button>
                <button onClick={() => slider?.current?.slickNext()}><img src="/icons/right.png"/></button>
              </div>
              <div className="col-md-6 col-6 text-end">
                <a href="#"><button>View all</button></a>
              </div>
            </div>
          </div>
        </main>

        <section className={styles.bgblack}>
          <div className="container">
            <div className={"row " + styles.excRange}>
              <div className={"col-md-3 " }>
                <Slider ref={excRangeslider} {...excRangesettings1}>
                  <div>
                    <img src="/home/sd1.png"/>
                  </div>
                  <div>
                    <img src="/home/sd2.png"/>
                  </div>
                  <div>
                    <img src="/home/sd3.png"/>
                  </div>
                  <div>
                    <img src="/home/sd1.png"/>
                  </div>
                  <div>
                    <img src="/home/sd2.png"/>
                  </div>
                  <div>
                    <img src="/home/sd3.png"/>
                  </div>
                </Slider>
              </div>
              <div className={"col-md-3 " }>
                <Slider ref={excRangeslider} {...excRangesettings2}>
                  <div>
                    <img src="/home/sd1.png"/>
                  </div>
                  <div>
                    <img src="/home/sd2.png"/>
                  </div>
                  <div>
                    <img src="/home/sd3.png"/>
                  </div>
                  <div>
                    <img src="/home/sd1.png"/>
                  </div>
                  <div>
                    <img src="/home/sd2.png"/>
                  </div>
                  <div>
                    <img src="/home/sd3.png"/>
                  </div>
                </Slider>
              </div>
              <div className="col-md-6">
                <div className={"row justify-content-center align-items-center" }>
                  <div className={styles.width405}>
                    <div className={"row "+ styles.mb35}>
                      <div className="col-md-12 p-0">
                        <h2 className={styles.mb35}>Introducing <br/><span>Our Exclusive Range</span></h2>
                        <p>All new collection for your dream home. This is a breakthrough of traditional design. The basin forms a 75 degree angle with the counter to break the space balance.</p>
                      </div>
                    </div>
                    <div className="row ">
                      <div className="col-md-6 col-6 p-0">
                        <button onClick={() => excRangeslider?.current?.slickPrev()}><img src="/icons/left.png"/></button>
                        <button onClick={() => excRangeslider?.current?.slickNext()}><img src="/icons/right.png"/></button>
                      </div>
                      <div className="col-md-6 col-6 p-0 text-end">
                        <a href="#"><button>View all</button></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        
        <section className={styles.premium}>
          <div className="container">
            <div className={"row " + styles.preTiles}>
              <h3>Premium <span>Tiles & Ceramics</span></h3>
              <div className={"col-md-8 " + styles.mb30}>
                <div className={"row " }>
                  <div className="col-md-5">
                  <div>
                    <img src="/home/p1.png"/>
                  </div>
                  </div>
                  <div className="col-md-7">
                    <h2 className={styles.mb35}>Ivory Floor Tiles</h2>
                    <p>As the era of 'less is more' is fading, many look for new ways to express their personality in their private spaces. Some tips below on how to personalise your bathroom, by giving it a bold look through stylised fixtures and unconventional finishes.</p>
                  </div>
                </div>
              </div>
              <div className={"col-md-12 " + styles.mb30}>
                <Slider ref={preSlider} {...preSettings}>
                  <div>
                    <div className={styles.slideInd}>
                    <img src="/home/p2.png"/>
                    <p>Terrazzo Countertop <br/><span>Wash Basin STL-1905-GR-WB - Grey</span></p>
                    </div>
                  </div>
                  <div>
                    <div className={styles.slideInd}>
                      <img src="/home/p3.png"/>
                      <p>Filita Close Coupled WC <br/><span>STL-1900-GR-FC - Crome</span></p>
                    </div>
                  </div>
                  <div>
                    <div className={styles.slideInd}>
                      <img src="/home/p4.png"/>
                      <p>Marble Countertop Wash Basin<br/><span> STL-1906-GR-WB - White</span></p>
                    </div>
                  </div>
                  <div>
                    <div className={styles.slideInd}>
                      <img src="/home/p2.png"/>
                      <p>Terrazzo Countertop <br/><span>Wash Basin STL-1905-GR-WB - Grey</span></p>
                    </div>
                  </div>
                  <div>
                    <div className={styles.slideInd}>
                      <img src="/home/p3.png"/>
                      <p>Filita Close Coupled WC <br/><span>STL-1900-GR-FC - Crome</span></p>
                    </div>
                  </div>
                  <div>
                    <div className={styles.slideInd}>
                      <img src="/home/p4.png"/>
                      <p>Marble Countertop Wash Basin<br/><span> STL-1906-GR-WB - White</span></p>
                    </div>
                  </div>
                </Slider>
              </div>
              <div className="col-md-6 col-6">
                <button onClick={() => preSlider?.current?.slickPrev()}><img src="/icons/left.png"/></button>
                <button onClick={() => preSlider?.current?.slickNext()}><img src="/icons/right.png"/></button>
              </div>
              <div className="col-md-6 col-6 text-end">
                <a href="#"><button>View all Products</button></a>
              </div>
              
            </div>
          </div>
        </section>

        <section className={"slidenavLine " + styles.bgImg}>
          <div className="container">
            <div className={"row " + styles.bgSlide}>
              <div className={"col-md-12 " }>
                <Slider {...bgSlidesettings}>
                  <div>
                    <div className={styles.carouselItem}>
                      <img src="/home/g1.png"/>
                      <div className={styles.carouselCaption}>
                        <h2>German <br/><span>Perfected Design</span></h2>
                        <p>Designed and tuned with Stratoz concepts, Designing with humble shades of black and white is as exciting as it would be challenging.</p>
                      </div>
                    </div>
                  </div>
                  <div>
                    <div className={styles.carouselItem}>
                      <img src="/home/g1.png"/>
                      <div className={styles.carouselCaption}>
                        <h2>German <br/><span>Perfected Design</span></h2>
                        <p>Designed and tuned with Stratoz concepts, Designing with humble shades of black and white is as exciting as it would be challenging.</p>
                      </div>
                    </div>
                  </div>
                  <div>
                    <div className={styles.carouselItem}>
                      <img src="/home/g1.png"/>
                      <div className={styles.carouselCaption}>
                        <h2>German <br/><span>Perfected Design</span></h2>
                        <p>Designed and tuned with Stratoz concepts, Designing with humble shades of black and white is as exciting as it would be challenging.</p>
                      </div>
                    </div>
                  </div>
                </Slider>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.flipSect}>
          <div className="container">
            <div className="row">
              <div className="col-md-3 ">
                <div className={styles.flipMain}>
                  <img src="/home/f1.png"/>
                  <h2>Timeless Designs</h2>
                </div>
              </div>
              <div className="col-md-9 p-0">
                <div className={"row " + styles.row1}>
                  <div className="col-md-4 p-0">
                    <div className={styles.flipImg}>
                      <img src="/home/f2.png"/>
                    </div>
                  </div>
                  <div className="col-md-4 p-0">
                    <div className={styles.flipImg}>
                      <img src="/home/f3.png"/>
                    </div>
                  </div>
                  <div className={"col-md-4 p-0 " + styles.bgTitle1}>
                    <div className={styles.flipTitle}>
                      <h6>Classic Black <br/>Interior</h6>
                    </div>
                  </div>
                </div>
                <div className={"row " + styles.row2}>
                  <div className={"col-md-4 p-0 " + styles.bgTitle2}>
                    <div className={styles.flipcontent}>
                      <p>Envision the future of bathware</p>
                      <a><button>View all</button></a>
                    </div>
                  </div>
                  <div className={"col-md-4 p-0 " + styles.bgTitle3}>
                    <div className={styles.flipcontent}>
                      <p>Designed and tuned with Stratoz concepts, Designing with humble shades of black and white is as exciting as it would be challenging.</p>
                    </div>
                  </div>
                  <div className="col-md-4 p-0">
                    <div className="flipImg">
                      <img src="/home/f4.png"/>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        
        <section className={styles.bgblack}>
          <div className="container">
            <div className={"row " + styles.simDesign}>
              <div className="col-md-6">
                <div className={"row justify-content-center align-items-center" }>
                  <div className={styles.width365}>
                    <div className={"row "+ styles.mb35}>
                      <div className="col-md-12 p-0">
                        <h2 className={styles.mb35}>Simple Design <br/><span>Modern Bath ware <br/>Solutions</span></h2>
                        <p>Weather traditional or contemporary, a faucet that bears the name stratoz carries with it the pride of having been designed to be exceptional on its own way, and each collection is perfectly proportioned.</p>
                      </div>
                    </div>
                    <div className="row ">
                      <div className="col-md-6 col-6 p-0">
                        <button onClick={() => simDesignslider?.current?.slickPrev()}><img src="/icons/left.png"/></button>
                        <button onClick={() => simDesignslider?.current?.slickNext()}><img src="/icons/right.png"/></button>
                      </div>
                      <div className="col-md-6 col-6 p-0 text-end">
                        <a href="#"><button>View all</button></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={"col-md-6 " }>
              <Slider ref={simDesignslider} {...simDesignsettings}>
                <div>
                  <img src="/home/sd1.png"/>
                </div>
                <div>
                  <img src="/home/sd2.png"/>
                </div>
                <div>
                  <img src="/home/sd3.png"/>
                </div>
                <div>
                  <img src="/home/sd1.png"/>
                </div>
                <div>
                  <img src="/home/sd2.png"/>
                </div>
                <div>
                  <img src="/home/sd3.png"/>
                </div>
              </Slider>
              </div>
            </div>
          </div>
        </section>
      </LayoutDefault>
    </>
  );
};

export default Home;
