import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../layout/Default";
import styles from "../../styles/Warranty.module.scss";
import Hero from "../components/Warranty/Hero";
import React, { Component } from "react";

const Showroom: NextPage = () => {
  return (
    <>
      <LayoutDefault>
        <Hero />
        <div className={styles.container}>
          <Head>
            <title>Stratos</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.title_desc}>
              <div className={"container " }>
                <h2 className={styles.h2_title}>
                  <span>Warranty </span> Registration
                </h2>
                <hr/>
                <form className={styles.formBox+" "+styles.mt30}>
                  <div className={styles.row}>
                    <div className={styles.col6}>
                      <label>First Name</label>
                      <input type="text" placeholder="Jonathan "/>
                    </div>
                    <div className={styles.col6}>
                      <label>Last Name</label>
                      <input type="text" placeholder="Doe"/>
                    </div>
                  </div>
                  <div className={styles.row}>
                    <div className={styles.col6}>
                      <label>Email ID</label>
                      <input type="email" placeholder="jon.doe@gmail.com "/>
                    </div>
                    <div className={styles.col6}>
                      <label>Phone Number</label>
                      <input type="text" placeholder="9731111000"/>
                    </div>
                  </div>
                  <div className={styles.row}>
                    <div className={styles.col6}>
                      <label>Purchased From</label>
                      <select>
                        <option>Ababeel Emporio</option>
                        <option>Ababeel Emporio</option>
                      </select>
                    </div>
                    <div className={styles.col6}>
                      <label>Date of Purchase</label>
                      <input type="date" placeholder="Doe"/>
                    </div>
                  </div>
                  <div className={styles.row}>
                    <div className={styles.col6}>
                      <label>Upload Invoice</label>
                      <div className="fileUpload">
                        <input type="file" />
                        <img src=""/>
                      </div>
                    </div>
                    <div className={styles.col6}>
                      <label>Product Code</label>
                      <input type="text" placeholder="LoreumIpsum"/>
                    </div>
                  </div>
                  <div className={styles.row}>
                    <div className={styles.col12+" "+styles.txtrgt}>
                      <input type="submit" value="Submit" />
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </main>
        </div>
      </LayoutDefault>
    </>
  );
};

export default Showroom;
