import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LayoutDefault from "../../../layout/Default";
import styles from "../../../../styles/Products.module.scss";
import router from "next/router";
import axios from "axios";
import api from "../../../api";
import { useState } from "react";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { selectUser } from "../../../features/auth/authSlice";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCoffee } from "@fortawesome/free-solid-svg-icons";

const HeartOutlineIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-6 w-6"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
    height="22px"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
    />
  </svg>
);

const HeartSolidIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-5 w-5"
    viewBox="0 0 20 20"
    fill="currentColor"
    height="22px"
  >
    <path
      fillRule="evenodd"
      d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
      clipRule="evenodd"
    />
  </svg>
);

const Products: NextPage = ({ product, slug }: any) => {
  const [isFavourite, setisFavourite] = useState(false);

  const { user } = useSelector(selectUser);

  const handleFavourites = () => {
    const body = { products: product.id };

    if (isFavourite) {
      api.delete(`/unfavorite/${product.id}`).then(() => {
        setisFavourite(false);
      });
    } else {
      api.post(`/favorite`, body).then(() => {
        setisFavourite(true);
      });
    }
  };

  useEffect(() => {
    if (!user) return;

    api.get(`/check-favorite/${product.id}`).then(({ data }) => {
      console.log(data);

      setisFavourite(data.favorite);
    });
  }, [product.id, user]);

  return (
    <>
      <LayoutDefault>
        {console.log(product)}
        <div className={styles.container}>
          <Head>
            <title>Stratoz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <br />
        <br />
        <br />
        <div className="mb-5"></div>
        <div className="mt-5"></div>
        <div className="container">
          <div className="row py-5">
            <div className="col-lg-5">
              <Image
                src={
                  product?.images.length !== 0
                    ? process.env.NEXT_PUBLIC_API_BASE_URL +
                      product.images[0].url
                    : `${process.env.NEXT_PUBLIC_API_BASE_URL}/uploads/counter_basin_500x500_2f4fee6d5e.PNG`
                }
                height={340}
                width={340}
                alt={"sddsd"}
              />
            </div>
            <div className="col-lg-7">
              {console.log(product)}
              <h1 className="product__title mb-4">{product.title}</h1>
              <h4>Product description</h4>
              <p>{product.code}</p>
              <p>
                SIZE: {product.size.Height} x {product.size.Width} x{" "}
                {product.size.Length} MM
              </p>
              {product.avail_colours.length > 0 && (
                <div className="d-flex align-items-center">
                  <span className="me-3">Color:</span>
                  {product.avail_colours.map((item: any, index: number) => (
                    <a href={`/products/${item.product.slug}`} key={index}>
                      <div
                        key={index}
                        className="me-2"
                        style={{
                          height: "30px",
                          width: "30px",
                          backgroundColor: item.colour.code,
                          border: "1px solid #000",
                        }}
                      ></div>
                    </a>
                  ))}
                </div>
              )}
              <div className="d-flex mt-4">
                <div
                  className="btn btn-primary me-3"
                  onClick={handleFavourites}
                >
                  {/* <span>
                    <FontAwesomeIcon icon={faCoffee} />
                  </span> */}
                  {isFavourite ? <HeartSolidIcon /> : <HeartOutlineIcon />}
                  <span className="ms-2">Add to Favourites</span>
                </div>
                <div
                  className="btn btn-outline-primary"
                  onClick={() => router.push(`/products/${slug}/enquire`)}
                >
                  Enquiry
                </div>
              </div>
              <div className="mt-5 mb-3">
                {product.technical_specs && (
                  <a
                    href={
                      process.env.NEXT_PUBLIC_API_BASE_URL +
                      product.technical_specs.url
                    }
                    download
                  >
                    Technical specifications
                  </a>
                )}
              </div>
              <div>
                <h5 className="mb-4">Share this on</h5>
                <div className="d-flex">
                  <div className="social__media__icons">
                    <FontAwesomeIcon
                      icon={faCoffee}
                      style={{ color: "#fff" }}
                    />
                  </div>
                  <div className="social__media__icons">
                    <FontAwesomeIcon
                      icon={faCoffee}
                      style={{ color: "#fff" }}
                    />
                  </div>
                  <div className="social__media__icons">
                    <FontAwesomeIcon
                      icon={faCoffee}
                      style={{ color: "#fff" }}
                    />
                  </div>
                  <div className="social__media__icons">
                    <FontAwesomeIcon
                      icon={faCoffee}
                      style={{ color: "#fff" }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container"></div>
        <br />
        <br />
        <div className="bg-light py-5">
          <div className="container">
            <h3 className="section__title mb-5">
              <span>Related</span> Products
            </h3>
            <div className="d-flex justify-content-between">
              {product?.related_products.map((item: any, index: number) => (
                <div key={index}>
                  <Image
                    src={
                      item.images.length !== 0
                        ? process.env.NEXT_PUBLIC_API_BASE_URL +
                          item.images[0].url
                        : `${process.env.NEXT_PUBLIC_API_BASE_URL}/uploads/counter_basin_500x500_2f4fee6d5e.PNG`
                    }
                    height={340}
                    width={340}
                    alt={"sddsd"}
                  />
                  <h3>{item.title}</h3>
                  <div>{item.code} </div>
                  <br />
                </div>
              ))}
            </div>
          </div>
        </div>
        <div className="container"></div>
      </LayoutDefault>
    </>
  );
};

export async function getServerSideProps({ query }: any) {
  // Fetch product list form API
  const productRes = await fetch(
    `${process.env.API_BASE_URL}/products/${query.slug}/`
  );

  const product = await productRes.json();

  // Pass data to the page via props
  return { props: { product, slug: query.slug } };
}

export default Products;
